library(rvest)
library(dplyr)
library(stringr)
library(robotstxt)
url <- 'https://www.forbes.com/lists/ai50/?sh=68a76594290f'
web <- read_html(url)
View(web)
Ai_name<- web %>% html_nodes('.name') %>% html_text()
View(Ai_name)
headquarters<- web %>% html_nodes('.headquarters') %>% html_text()
View(headquarters)
ceo <- web %>% html_nodes('.ceo') %>% html_text()
View(ceo)
Year_founded <- web %>% html_nodes('.founded') %>% html_text()
View(Year_founded)
data_1 = data.frame(Ai_name,headquarters,ceo,Year_founded)
View(data_1)
write.csv(data_1,"Ai-List.csv")
